import { Student, AIInsight, DashboardMetrics } from '@/types/coachpass';

export const mockDashboardMetrics: DashboardMetrics = {
  totalStudents: 24,
  activeStudents: 19,
  warningStudents: 5,
  avgAdherenceRate: 88,
  totalWorkoutsThisMonth: 184,
  aiInsightsCount: 4,
};

export const mockStudents: Student[] = [
  {
    id: 'std-1',
    name: 'Lucas Silva',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    email: 'lucas.silva@email.com',
    phone: '(11) 98765-4321',
    goal: 'Hipertrofia & Ganho de Massa',
    joinedDate: '15/01/2026',
    status: 'warning',
    adherencePercentage: 62,
    frequencyPerWeek: 2,
    expectedFrequencyPerWeek: 4,
    currentWeightKg: 78.5,
    targetWeightKg: 82.0,
    workoutsCompletedThisMonth: 8,
    recentWorkouts: [
      {
        id: 'w-101',
        date: '24/08/2026',
        title: 'Treino A - Peitoral & Tríceps',
        durationMinutes: 55,
        rpe: 8,
        exercises: [
          { id: 'ex-1', name: 'Supino Reto', muscleGroup: 'Peitoral', sets: 4, reps: 10, weightKg: 80, previousWeightKg: 80 },
          { id: 'ex-2', name: 'Supino Inclinado c/ Halteres', muscleGroup: 'Peitoral', sets: 3, reps: 12, weightKg: 28, previousWeightKg: 26 },
          { id: 'ex-3', name: 'Tríceps Pulley', muscleGroup: 'Tríceps', sets: 4, reps: 12, weightKg: 35, previousWeightKg: 35 },
        ],
      },
      {
        id: 'w-102',
        date: '20/08/2026',
        title: 'Treino B - Costas & Bíceps',
        durationMinutes: 60,
        rpe: 7,
        exercises: [
          { id: 'ex-4', name: 'Puxada Frontal', muscleGroup: 'Costas', sets: 4, reps: 10, weightKg: 65, previousWeightKg: 65 },
          { id: 'ex-5', name: 'Remada Curvada', muscleGroup: 'Costas', sets: 4, reps: 8, weightKg: 70, previousWeightKg: 68 },
        ],
      },
    ],
  },
  {
    id: 'std-2',
    name: 'Camila Oliveira',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=200',
    email: 'camila.oliveira@email.com',
    phone: '(11) 97654-3210',
    goal: 'Definição & Força',
    joinedDate: '02/02/2026',
    status: 'active',
    adherencePercentage: 96,
    frequencyPerWeek: 5,
    expectedFrequencyPerWeek: 5,
    currentWeightKg: 62.0,
    targetWeightKg: 60.0,
    workoutsCompletedThisMonth: 20,
    recentWorkouts: [
      {
        id: 'w-201',
        date: '25/08/2026',
        title: 'Treino Leg Day - Glúteos & Quadríceps',
        durationMinutes: 65,
        rpe: 9,
        exercises: [
          { id: 'ex-6', name: 'Agachamento Livre', muscleGroup: 'Quadríceps', sets: 4, reps: 8, weightKg: 95, previousWeightKg: 90 },
          { id: 'ex-7', name: 'Elevação Pélvica', muscleGroup: 'Glúteos', sets: 4, reps: 10, weightKg: 130, previousWeightKg: 120 },
          { id: 'ex-8', name: 'Leg Press 45°', muscleGroup: 'Quadríceps', sets: 3, reps: 12, weightKg: 200, previousWeightKg: 190 },
        ],
      },
    ],
  },
  {
    id: 'std-3',
    name: 'Rodrigo Mendes',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    email: 'rodrigo.mendes@email.com',
    phone: '(21) 99887-6655',
    goal: 'Condicionamento & Emagrecimento',
    joinedDate: '10/03/2026',
    status: 'active',
    adherencePercentage: 90,
    frequencyPerWeek: 4,
    expectedFrequencyPerWeek: 4,
    currentWeightKg: 91.2,
    targetWeightKg: 85.0,
    workoutsCompletedThisMonth: 16,
    recentWorkouts: [
      {
        id: 'w-301',
        date: '24/08/2026',
        title: 'Treino Full Body & Metcon',
        durationMinutes: 50,
        rpe: 9,
        exercises: [
          { id: 'ex-9', name: 'Levantamento Terra', muscleGroup: 'Posterior/Costas', sets: 4, reps: 6, weightKg: 120, previousWeightKg: 115 },
          { id: 'ex-10', name: 'Kettlebell Swings', muscleGroup: 'Core/Full', sets: 4, reps: 20, weightKg: 24, previousWeightKg: 20 },
        ],
      },
    ],
  },
  {
    id: 'std-4',
    name: 'Beatriz Costa',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200',
    email: 'beatriz.costa@email.com',
    phone: '(31) 98877-4433',
    goal: 'Reabilitação & Fortalecimento Core',
    joinedDate: '01/05/2026',
    status: 'warning',
    adherencePercentage: 55,
    frequencyPerWeek: 1,
    expectedFrequencyPerWeek: 3,
    currentWeightKg: 58.0,
    targetWeightKg: 58.0,
    workoutsCompletedThisMonth: 5,
    recentWorkouts: [
      {
        id: 'w-401',
        date: '18/08/2026',
        title: 'Postural & Fortalecimento de Coluna',
        durationMinutes: 45,
        rpe: 6,
        exercises: [
          { id: 'ex-11', name: 'Prancha Isométrica', muscleGroup: 'Core', sets: 4, reps: 45, weightKg: 0, previousWeightKg: 0 },
          { id: 'ex-12', name: 'Perdigueiro com Carga', muscleGroup: 'Core', sets: 3, reps: 12, weightKg: 2, previousWeightKg: 2 },
        ],
      },
    ],
  },
  {
    id: 'std-5',
    name: 'Gabriel Ferraz',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    email: 'gabriel.ferraz@email.com',
    phone: '(11) 99112-2334',
    goal: 'Preparação Atlética (Triathlon)',
    joinedDate: '12/11/2025',
    status: 'active',
    adherencePercentage: 98,
    frequencyPerWeek: 6,
    expectedFrequencyPerWeek: 6,
    currentWeightKg: 72.0,
    targetWeightKg: 71.5,
    workoutsCompletedThisMonth: 24,
    recentWorkouts: [
      {
        id: 'w-501',
        date: '25/08/2026',
        title: 'Treino de Força Específica Leg Drive',
        durationMinutes: 50,
        rpe: 8,
        exercises: [
          { id: 'ex-13', name: 'Agachamento Búlgaro', muscleGroup: 'Quadríceps', sets: 4, reps: 10, weightKg: 24, previousWeightKg: 22 },
        ],
      },
    ],
  },
];

export const mockAIInsights: AIInsight[] = [
  {
    id: 'ai-1',
    studentId: 'std-1',
    studentName: 'Lucas Silva',
    studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    type: 'risk',
    severity: 'high',
    title: 'Queda Crítica na Frequência',
    description: 'Lucas treinou apenas 2x por semana nas últimas 2 semanas (meta: 4x). A adesão caiu para 62%. Risco de evasão nos próximos 15 dias.',
    date: 'Hoje, 09:30',
    actionRequired: 'Enviar mensagem de acompanhamento ou agendar alinhamento de rotina.',
  },
  {
    id: 'ai-2',
    studentId: 'std-2',
    studentName: 'Camila Oliveira',
    studentAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=200',
    type: 'achievement',
    severity: 'low',
    title: 'Novo Recorde Pessoal (PR) de Carga',
    description: 'Camila aumentou 5.5% no Agachamento Livre (95kg para 8 reps), superando o recorde anterior. Progressão de carga excelente.',
    date: 'Hoje, 08:15',
    actionRequired: 'Enviar mensagem de parabenização e avaliar inclusão de semana de deload em breve.',
  },
  {
    id: 'ai-3',
    studentId: 'std-4',
    studentName: 'Beatriz Costa',
    studentAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200',
    type: 'retention',
    severity: 'medium',
    title: 'Sem Registro de Treino há 7 dias',
    description: 'Nenhuma sessão registrada desde 18/08. O histórico aponta desconforto muscular recente na região lombar.',
    date: 'Ontem, 18:40',
    actionRequired: 'Verificar se houve dor ou imprevisto de saúde e reajustar o plano postural.',
  },
  {
    id: 'ai-4',
    studentId: 'std-3',
    studentName: 'Rodrigo Mendes',
    studentAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    type: 'suggestion',
    severity: 'low',
    title: 'Recomendação de Progressão no Terra',
    description: 'Rodrigo completou 4 séries de 6 reps a 120kg com RPE 7 (percepção de esforço moderada). A IA sugere subir para 125kg na próxima sessão.',
    date: 'Ontem, 14:10',
    actionRequired: 'Atualizar ficha de treino com nova meta de carga.',
  },
];
