/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gvcxexgzrduhwucealco"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2Y3hleGd6cmR1aHd1Y2VhbGNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NzY2MTAsImV4cCI6MjA4ODI1MjYxMH0.cBY6yj5GYRXwehR3QFvbxy5LldqQ-Yn2-RT4L8uyzgs"