/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'student-profiles': StudentProfile;
    'professional-links': ProfessionalLink;
    workouts: Workout;
    'meal-plans': MealPlan;
    'ai-generations': AiGeneration;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'student-profiles': StudentProfilesSelect<false> | StudentProfilesSelect<true>;
    'professional-links': ProfessionalLinksSelect<false> | ProfessionalLinksSelect<true>;
    workouts: WorkoutsSelect<false> | WorkoutsSelect<true>;
    'meal-plans': MealPlansSelect<false> | MealPlansSelect<true>;
    'ai-generations': AiGenerationsSelect<false> | AiGenerationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Concede o mesmo poder do papel Master no CMS e libera todos os painéis no app.
   */
  isSuperAdmin?: boolean | null;
  role?: ('master' | 'student' | 'personal' | 'nutritionist') | null;
  whatsapp?: string | null;
  professionalId?: string | null;
  plan?: ('free' | 'monthly' | 'semester' | 'annual') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-profiles".
 */
export interface StudentProfile {
  id: number;
  user: number | User;
  displayName: string;
  phone: string;
  birthDate: string;
  heightCm: number;
  weightKg: number;
  sex: 'male' | 'female' | 'other' | 'undisclosed';
  goal: 'weight_loss' | 'hypertrophy';
  bodyFatPercent?: number | null;
  experienceLevel?: ('beginner' | 'intermediate' | 'advanced') | null;
  trainingDaysPerWeek?: number | null;
  sessionMinutes?: number | null;
  equipmentAccess?: ('full_gym' | 'basic_gym' | 'home_weights' | 'bodyweight' | 'outdoor')[] | null;
  foodAllergies?: string | null;
  dietaryRestrictions?: string | null;
  medicalConditions?: string | null;
  injuries?: string | null;
  medications?: string | null;
  onboardingCompleted?: boolean | null;
  onboardingCompletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "professional-links".
 */
export interface ProfessionalLink {
  id: number;
  student: number | User;
  professional: number | User;
  professionalRole: 'personal' | 'nutritionist';
  status: 'pending' | 'active' | 'revoked';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workouts".
 */
export interface Workout {
  id: number;
  title: string;
  student: number | User;
  author?: (number | null) | User;
  status: 'draft' | 'published';
  source: 'professional' | 'ai';
  observations?: string | null;
  weekday?: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday') | null;
  splitLabel?: string | null;
  publishedAt?: string | null;
  exercises?:
    | {
        name: string;
        sets?: number | null;
        reps?: string | null;
        weight?: string | null;
        rest?: string | null;
        muscle?: string | null;
        notes?: string | null;
        instructions?: string | null;
        youtubeUrl?: string | null;
        muscleImage?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meal-plans".
 */
export interface MealPlan {
  id: number;
  title: string;
  student: number | User;
  author?: (number | null) | User;
  status: 'draft' | 'published';
  source: 'professional' | 'ai';
  observations?: string | null;
  isInformational?: boolean | null;
  publishedAt?: string | null;
  meals?:
    | {
        name: string;
        time?: string | null;
        calories?: number | null;
        notes?: string | null;
        items?:
          | {
              name: string;
              quantity?: string | null;
              calories?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-generations".
 */
export interface AiGeneration {
  id: number;
  user: number | User;
  type: 'workout' | 'meal_plan';
  status: 'pending' | 'succeeded' | 'failed' | 'blocked';
  provider?: string | null;
  errorMessage?: string | null;
  /**
   * ID do workout ou meal-plan gerado
   */
  resultId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'student-profiles';
        value: number | StudentProfile;
      } | null)
    | ({
        relationTo: 'professional-links';
        value: number | ProfessionalLink;
      } | null)
    | ({
        relationTo: 'workouts';
        value: number | Workout;
      } | null)
    | ({
        relationTo: 'meal-plans';
        value: number | MealPlan;
      } | null)
    | ({
        relationTo: 'ai-generations';
        value: number | AiGeneration;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  isSuperAdmin?: T;
  role?: T;
  whatsapp?: T;
  professionalId?: T;
  plan?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-profiles_select".
 */
export interface StudentProfilesSelect<T extends boolean = true> {
  user?: T;
  displayName?: T;
  phone?: T;
  birthDate?: T;
  heightCm?: T;
  weightKg?: T;
  sex?: T;
  goal?: T;
  bodyFatPercent?: T;
  experienceLevel?: T;
  trainingDaysPerWeek?: T;
  sessionMinutes?: T;
  equipmentAccess?: T;
  foodAllergies?: T;
  dietaryRestrictions?: T;
  medicalConditions?: T;
  injuries?: T;
  medications?: T;
  onboardingCompleted?: T;
  onboardingCompletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "professional-links_select".
 */
export interface ProfessionalLinksSelect<T extends boolean = true> {
  student?: T;
  professional?: T;
  professionalRole?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workouts_select".
 */
export interface WorkoutsSelect<T extends boolean = true> {
  title?: T;
  student?: T;
  author?: T;
  status?: T;
  source?: T;
  observations?: T;
  weekday?: T;
  splitLabel?: T;
  publishedAt?: T;
  exercises?:
    | T
    | {
        name?: T;
        sets?: T;
        reps?: T;
        weight?: T;
        rest?: T;
        muscle?: T;
        notes?: T;
        instructions?: T;
        youtubeUrl?: T;
        muscleImage?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meal-plans_select".
 */
export interface MealPlansSelect<T extends boolean = true> {
  title?: T;
  student?: T;
  author?: T;
  status?: T;
  source?: T;
  observations?: T;
  isInformational?: T;
  publishedAt?: T;
  meals?:
    | T
    | {
        name?: T;
        time?: T;
        calories?: T;
        notes?: T;
        items?:
          | T
          | {
              name?: T;
              quantity?: T;
              calories?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-generations_select".
 */
export interface AiGenerationsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  status?: T;
  provider?: T;
  errorMessage?: T;
  resultId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}